# Site settings
title: 
email: lailah@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lailahxuer.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username: lailahxuer

# Build settings
markdown: kramdown
